[project]
name = "mnist"
version = "0.1.0"
description = "Trabalho 2, perceptron multicamada"
authors = [{ name = "Datura", email = "daturasoldev@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch (>=2.7.0,<3.0.0)",
    "torchvision (>=0.22.0,<0.23.0)",
    "torchaudio (>=2.7.0,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
priority = "explicit"

[tool.poetry.dependencies]
torch = { source = "pytorch-cu128" }
torchvision = { source = "pytorch-cu128" }
torchaudio = { source = "pytorch-cu128" }
